### ISSUE TITLE
Issue with Spotify plugin

### ISSUE THREAD

**Issue by ashthespy** [tim-felix-lange/volumio-plugins#1]
I just stumbled upon this plugin, and it solves a similar issueI have, so thanks!

However, when using it with the Spotify plugin - the status quickly goes through a `play` - `stop` - `play`  routine when the track changes.

Would it be possible to add a small delay buffer so the GPIO is toggled only after `xx` seconds after stop? This could be user settable from the GUI.

**Comment by tim-felix-lange** [comment]
Issue solved by commit ff2a1e7
