### ISSUE TITLE
Issue with volspotconnect2

### ISSUE THREAD

**Issue by lgroeb** [tim-felix-lange/volumio-plugins#4]
Hi, this Plugin is a really great idea. Got it working on volumio2, latest release. It works for internet radio and music playback from USB. At the moment we are mainly listening to Spotify. Volspotconnect2 works great. However the ampswitch plugin is not interworking with volspotconnect2. Also AirPlay playback is not detected. It would be great, if at least volspotconnect2 could be supported.
Thanks and best regards

**Comment by tim-felix-lange** [comment]
@lgroeb The plugin works on the internal play/pause status exposed by Volumio. In my current configuration it works flawless with AirPlay. I can't test spotify, because I have no account there. If the issue still exists, I need some additional information. Please upload a log file where you started volspotconnect2 and where the ampswitch was not working as expected.

**Comment by lgroeb** [comment]
@tim-felix-lange Sorry for my late reply. Tested it quite a while ago. So I will do a new install my Rasp2 with the latest sofware and plugins and then will do a new test. I will get back to you (most probably within a week).

**Comment by lgroeb** [comment]
@tim-felix-lange So i did the test as follows: Clean install of latest image for raspberry pi 2. Install latest version of volspotconnect2 (0.4.0 I think). Install latest version of amp switch plugin. Then I activated both plugins with default values. Added some web radio stations. Shut down. Then boot raspberry. Play / stop of web radio -- all works fine (switch from 0V to 3.3V on GPIO 14). Connect via airplay. Start / stop of a song  -- all works fine (switch from 0V to 3.3V on GPIO 14). Disconnect Airplay. Now I connected via volspotconnect2 and Start / Stop -- does not work. Nothing changes on GPIO 14. (Tried it several times). So to sum up: Airplay works great but volspotconnect2 does not work. If the plugin would work also for volspotconnect2 that would be absolutely great. So I would highly appreciate your help. Appended please find the log file. If you would need my help doing more tests, generating more logs, please let me know. Thanks and best regards.

[GtFioV4.zip](https://github.com/tim-felix-lange/volumio-plugins/files/1304094/GtFioV4.zip)

**Comment by lgroeb** [comment]
Sorry, forgot one thing to say: After trying volspotconnect2 I retried airplay. And with airplay everything was working fine again. So you will find some successful switch on and off at the end of the log file.

**Comment by tim-felix-lange** [comment]
Thanks for the log file. This supported my initial feeling, that it was rather a bug of volspotconnect2 than AmpSwitch. The AmpSwitch plugin itself is pretty stupid: It just listens to the information broadcasted by the volumio command router. As it's so simple, it's also pretty stable. The problem is, that volspotconnect2 does not properly interact with the volumio master, who then can not propagate this information to plugins like AmpSwitch. I was able to narrow the output of volspotconnect2 down to the following lines

> Sep 14 18:05:09 volumio volumio[992]: INFO:librespot_core::session: Connecting to AP "lon3-accesspoint-a51.ap.spotify.com:4070"
Sep 14 18:05:09 volumio volumio[992]: INFO:librespot_core::session: Authenticated as "lgroeb" !
Sep 14 18:05:09 volumio volumio[992]: INFO:librespot::audio_backend::alsa: Using alsa sink
Sep 14 18:05:09 volumio volumio[992]: INFO:librespot_core::session: Country: "DE"
Sep 14 18:05:10 volumio volumio[992]: INFO:librespot::player: Loading track "Lovers"
Sep 14 18:05:10 volumio volumio[992]: INFO:librespot::player: Track "Lovers" loaded

As you can see, there was no output of volumio. However, every time the core command router issues a push state message, you will see something like

>Sep 14 18:04:43 volumio volumio[881]: info: CoreCommandRouter::volumioPushState

For further status of fixing this issue, please refer to [Issue #83 of volspotconnect2](https://github.com/balbuze/volumio-plugins/issues/83).

**Comment by lgroeb** [comment]
Great, thank you very much for your fast reply and analysis. Highly appreciated. Let's see whether voldpotconnect can fix it. Best regards lgroeb


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Tim Lange <notifications@github.com> 
Datum: 15.09.17  15:06  (GMT+01:00) 
An: tim-felix-lange/volumio-plugins <volumio-plugins@noreply.github.com> 
Cc: lgroeb <christian.legl@web.de>, Mention <mention@noreply.github.com> 
Betreff: Re: [tim-felix-lange/volumio-plugins] Issue with volspotconnect2 (#4) 

Thanks for the log file. This supported my initial feeling, that it was rather a bug of volspotconnect2 than AmpSwitch. The AmpSwitch plugin itself is pretty stupid: It just listens to the information broadcasted by the volumio command router. As it's so simple, it's also pretty stable. The problem is, that volspotconnect2 does not properly interact with the volumio master, who then can not propagate this information to plugins like AmpSwitch. I was able to narrow the output of volspotconnect2 down to the following lines

Sep 14 18:05:09 volumio volumio[992]: INFO:librespot_core::session: Connecting to AP "lon3-accesspoint-a51.ap.spotify.com:4070"

Sep 14 18:05:09 volumio volumio[992]: INFO:librespot_core::session: Authenticated as "lgroeb" !

Sep 14 18:05:09 volumio volumio[992]: INFO:librespot::audio_backend::alsa: Using alsa sink

Sep 14 18:05:09 volumio volumio[992]: INFO:librespot_core::session: Country: "DE"

Sep 14 18:05:10 volumio volumio[992]: INFO:librespot::player: Loading track "Lovers"

Sep 14 18:05:10 volumio volumio[992]: INFO:librespot::player: Track "Lovers" loaded

As you can see, there was no output of volumio. However, every time the core command router issues a push state message, you will see something like

Sep 14 18:04:43 volumio volumio[881]: info: CoreCommandRouter::volumioPushState

For further status of fixing this issue, please refer to Issue #83 of volspotconnect2.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tim-felix-lange/volumio-plugins","title":"tim-felix-lange/volumio-plugins","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tim-felix-lange/volumio-plugins"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tim-felix-lange in #4: Thanks for the log file. This supported my initial feeling, that it was rather a bug of volspotconnect2 than AmpSwitch. The AmpSwitch plugin itself is pretty stupid: It just listens to the information broadcasted by the volumio command router. As it's so simple, it's also pretty stable. The problem is, that volspotconnect2 does not properly interact with the volumio master, who then can not propagate this information to plugins like AmpSwitch. I was able to narrow the output of volspotconnect2 down to the following lines\r\n\r\n\u003e Sep 14 18:05:09 volumio volumio[992]: INFO:librespot_core::session: Connecting to AP \"lon3-accesspoint-a51.ap.spotify.com:4070\"\r\nSep 14 18:05:09 volumio volumio[992]: INFO:librespot_core::session: Authenticated as \"lgroeb\" !\r\nSep 14 18:05:09 volumio volumio[992]: INFO:librespot::audio_backend::alsa: Using alsa sink\r\nSep 14 18:05:09 volumio volumio[992]: INFO:librespot_core::session: Country: \"DE\"\r\nSep 14 18:05:10 volumio volumio[992]: INFO:librespot::player: Loading track \"Lovers\"\r\nSep 14 18:05:10 volumio volumio[992]: INFO:librespot::player: Track \"Lovers\" loaded\r\n\r\nAs you can see, there was no output of volumio. However, every time the core command router issues a push state message, you will see something like\r\n\r\n\u003eSep 14 18:04:43 volumio volumio[881]: info: CoreCommandRouter::volumioPushState\r\n\r\nFor further status of fixing this issue, please refer to [Issue #83 of volspotconnect2](https://github.com/balbuze/volumio-plugins/issues/83)."}],"action":{"name":"View Issue","url":"https://github.com/tim-felix-lange/volumio-plugins/issues/4#issuecomment-329777262"}}}
